apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: ">=1.0.0-alpha"
  test:
    enable: false
  values:
    # disabled for hub-and-spoke PoC on cluster 2 (no Gateway API CRDs / Redis dep)
    httpRoute:
      enabled: false
    redis:
      enabled: false
